name: Run Python Tests
on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple tdei-gtfs-csv-validator==0.0.31
      - name: Creating Env file
        run: |
          touch .env
          echo PROVIDER=Azure >> .env
          echo UPLOAD_TOPIC=test_subscription_topic >> .env
          echo VALIDATION_TOPIC=test_subscription_topic >> .env
          echo UPLOAD_SUBSCRIPTION=test_subscription >> .env
          echo STORAGECONNECTION=DefaultEndpointsProtocol=https;AccountName=tdeisamplestorage;AccountKey=l9JSJCGq9NrXqRVKApSk1wwV27aWaOVuxeY0NWOZz2svIlJzyncr3UFTzLoAanFbmJIeb2WmwIcS+AStj5gELg==;EndpointSuffix=core.windows.net >> .env
          echo QUEUECONNECTION=Endpoint=sb://tdei-service-bus.servicebus.windows.net/;SharedAccessKeyName=developer;SharedAccessKey=bddlcZHcH3sos3izTIYyaZTpapFRoVHwjOkfCZPdSxk=;EntityPath=gtfs-flex-upload >> .env
      - name: Run tests
        run: |
          coverage run --source=src -m unittest discover -s tests
          coverage report
