name: Unit Tests

#############################
# Start the job on all push #
#############################
on:
  push:
  pull_request:
    branches: [master, dev]

###############
# Set the Job #
###############
jobs:
  Setup:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Virtual Environment
        run: |
          python3.10 -m venv .venv
          source .venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple tdei-gtfs-csv-validator==0.0.31

      - name: Unit Test Cases
        run: python test_report.py
